name: pymatgen_contrib
dependencies:
- certifi=2016.2.28=py36_0
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.2=0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zlib=1.2.11=0
- pip:
  - alabaster==0.7.12
  - appdirs==1.4.3
  - ase==3.19.0
  - astroid==2.4.1
  - atomicwrites==1.3.0
  - attrs==19.3.0
  - babel==2.8.0
  - beautifulsoup4==4.8.2
  - black==19.3b0
  - bleach==3.1.5
  - cffi==1.14.0
  - chardet==3.0.4
  - click==7.0
  - configobj==5.0.6
  - coverage==5.0.2
  - cryptography==2.9.2
  - cycler==0.10.0
  - dataclasses==0.7
  - decorator==4.4.1
  - docutils==0.16
  - edx-dl==0.1.13
  - flamyngo (/users/knc6/anaconda2/envs/pymatgen_contrib/flamyngo)==0.10.6
  - flask==1.0.2
  - future==0.18.2
  - h5py==2.9.0
  - html5lib==1.0.1
  - idna==2.9
  - imageio==2.8.0
  - imagesize==1.2.0
  - importlib-metadata==1.6.0
  - itsdangerous==1.1.0
  - jarvis-tools (/users/knc6/Software/jarvis/usnistgov/jarvis)==2020.10.5
  - jarvisapps (/users/knc6/Software/jarvis_heterostruct)==2020.5.11
  - jeepney==0.4.3
  - jinja2==2.11.2
  - joblib==0.14.1
  - keyring==21.2.1
  - kiwisolver==1.1.0
  - lazy-object-proxy==1.4.3
  - lightgbm==2.1.0
  - livereload==2.6.1
  - lunr==0.5.6
  - markdown==3.2.2
  - markupsafe==1.1.1
  - matplotlib==3.1.2
  - mkdocs==1.1
  - monty==3.0.2
  - more-itertools==8.2.0
  - mpmath==1.1.0
  - networkx==2.4
  - nltk==3.5
  - numpy==1.17.2
  - packaging==20.3
  - palettable==3.3.0
  - pandas==0.25.3
  - pillow==7.0.0
  - pkginfo==1.5.0.1
  - pluggy==0.13.1
  - py==1.8.1
  - pycparser==2.20
  - pydispatcher==2.0.5
  - pyface==6.1.2
  - pygments==2.6.1
  - pymatgen (/users/knc6/anaconda2/envs/pymatgen_contrib/lib/python3.6/site-packages)==2020.1.10
  - pymongo==3.7.2
  - pyparsing==2.4.7
  - pytest==5.4.2
  - pytest-flask==1.0.0
  - python-dateutil==2.8.1
  - pytz==2020.1
  - pywavelets==1.1.1
  - pyyaml==5.1
  - readme-renderer==26.0
  - regex==2020.5.7
  - requests==2.23.0
  - requests-toolbelt==0.9.1
  - ruamel.yaml==0.16.5
  - ruamel.yaml.clib==0.2.0
  - scikit-image==0.16.2
  - scikit-learn==0.22.1
  - scipy==1.1.0
  - secretstorage==3.1.2
  - seekpath==1.9.4
  - simplejson==3.17.0
  - six==1.14.0
  - snowballstemmer==2.0.0
  - soupsieve==2.0
  - spglib==1.14.1.post0
  - sphinx==3.0.3
  - sphinx-autoapi==1.3.0
  - sphinxcontrib-applehelp==1.0.2
  - sphinxcontrib-devhelp==1.0.2
  - sphinxcontrib-htmlhelp==1.0.3
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-qthelp==1.0.3
  - sphinxcontrib-serializinghtml==1.1.4
  - sympy==1.5.1
  - tabulate==0.8.6
  - toml==0.10.0
  - toolz==0.10.0
  - tornado==6.0.4
  - tqdm==4.46.0
  - traits==6.0.0
  - traitsui==6.1.3
  - twine==3.1.1
  - typed-ast==1.4.1
  - unidecode==1.1.1
  - urllib3==1.25.9
  - wcwidth==0.1.9
  - webencodings==0.5.1
  - werkzeug==0.15.1
  - wrapt==1.12.1
  - xmltodict==0.12.0
  - youtube-dl==2020.3.1
  - zipp==3.1.0

